VeterinaryPassport/Models/Pet.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace VeterinaryPassport.Models
{
    public class Pet
    {
        public int Id { get; set; }
        [Display(Name = "Кличка")]
        [RegularExpression(@"[А-Я][а-я]+", ErrorMessage = "Некорректный ввод")]
        [Required(ErrorMessage = "Поле не указано")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Длина должна быть от 2 до 30 символов")]
        public string Name { get; set; }
        [Display(Name = "Вид")]
        [RegularExpression(@"[А-Я][а-я]+", ErrorMessage = "Некорректный ввод")]
        [Required(ErrorMessage = "Поле не указано")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Длина должна быть от 2 до 30 символов")]
        public string Kind { get; set; }
        [Display(Name = "Пол")]
        [Required(ErrorMessage = "Поле не указано")]
        public string Sex { get; set; }
        [Display(Name = "Порода")]
        [RegularExpression(@"[А-Я]([а-я]|\s|-)+", ErrorMessage = "Некорректный ввод")]
        [Required(ErrorMessage = "Поле не указано")]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "Длина должна быть от 5 до 30 символов")]
        public string Breed { get; set; }
        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Поле не указано")]
        public DateTime DOB { get; set; }
        //[AllowHtml]
        [Display(Name = "Фото питомца")]
        public string? ImageName { get; set; }
        public Passport? Passport { get; set; }
    }
}

VeterinaryPassport/Controllers/PetController.cs
using VeterinaryPassport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace VeterinaryPassport.Controllers
{
    [Authorize(Roles = "user")]
    public class PetController : Controller
    {
        Context db;
        public PetController(Context context)
        {
            db = context;
        }

        [HttpGet]
        public async Task<IActionResult> PetRead(string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var pet = db.Pets.Select(p => p);
            int pageSize = 5;

            return View(await Pagination<Pet>.CreatePaginationAsync(pet, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult PetCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PetCreate(Pet pet)
        {
            if (ModelState.IsValid)
            {
                await db.Pets.AddAsync(pet);
                await db.SaveChangesAsync();

                return RedirectToAction("PetRead");
            }
            return View(pet);
        }

        [HttpGet]
        public async Task<IActionResult> PetEdit(int? id)
        {
            if (id != null)
            {
                Pet pet = await db.Pets.FirstOrDefaultAsync(p => p.Id == id);
                if (pet != null)
                    return View(pet);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> PetEdit(Pet pet)
        {
            if (ModelState.IsValid)
            {
                db.Pets.Update(pet);
                await db.SaveChangesAsync();

                return RedirectToAction("PetRead");
            }
            return View(pet);
        }

        [HttpPost]
        public async Task<IActionResult> PetDelete(int? id)
        {
            if (id != null)
            {
                Pet pet = await db.Pets.FirstOrDefaultAsync(p => p.Id == id);
                db.Pets.Remove(pet);
                await db.SaveChangesAsync();

                return RedirectToAction("PetRead");
            }
            return NotFound();
        }
    }
}

VeterinaryPassport/Views/Pet/PetCreate.cshtml
@model VeterinaryPassport.Models.Pet

@{
    ViewBag.Title = "Добавление питомца";
}

<div class="create-and-edit-form">
    <form class="add-user-form" method="post" asp-controller="Pet" asp-action="PetCreate" asp-antiforgery="true">

        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Kind" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Kind" class="form-control" />
                <span asp-validation-for="Kind" class="text-danger"></span>
            </div>
        </div>
       <div class="form-group">
            <label asp-for="Sex" class="control-label"></label>
            <div class="form-group-container">
                <select asp-for="Sex" class="custom-select">
                    <option>Мужской</option>
                    <option>Женский</option>
                </select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Breed" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="DOB" class="control-label"></label>
            <div class="form-group-container">
                <input type="date" asp-for="DOB" value="1999-01-01" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Добавить" class="btn btn-outline-secondary" />
        </div>
    </form>
</div>

VeterinaryPassport/Views/Pet/PetEdit.cshtml
@model VeterinaryPassport.Models.Pet

@{
    ViewBag.Title = "Редактирование питомца";
}

<div class="create-and-edit-form">
    <form class="add-user-form" method="post" asp-controller="Pet" asp-action="PetEdit" asp-antiforgery="true">

        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Kind" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Kind" class="form-control" />
                <span asp-validation-for="Kind" class="text-danger"></span>
            </div>
        </div>
       <div class="form-group">
            <label asp-for="Sex" class="control-label"></label>
            <div class="form-group-container">
                <select asp-for="Sex" class="custom-select">
                    <option>Мужской</option>
                    <option>Женский</option>
                </select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Breed" class="control-label"></label>
            <div class="form-group-container">
                <input type="text" asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="DOB" class="control-label"></label>
            <div class="form-group-container">
                <input type="date" asp-for="DOB" value="1999-01-01" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
        </div>
    </form>
</div>

VeterinaryPassport/Views/Pet/PetRead.cshtml
@model Pagination<Pet>

@{
    ViewBag.Title = "Ветеринари";
}
  <a asp-action="PetCreate" class="btn btn-outline-secondary button-add">Добавить</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <p>@Html.DisplayNameFor(model => model.FirstOrDefault().Name)</p>
                </th>
                <th>
                    <p>@Html.DisplayNameFor(model => model.FirstOrDefault().Kind)</p>
                </th>
                <th>
                    <p>@Html.DisplayNameFor(model => model.FirstOrDefault().Sex)</p>
                </th>
                <th>
                    <p>@Html.DisplayNameFor(model => model.FirstOrDefault().Breed)</p>
                </th>
                <th>
                    <p>@Html.DisplayNameFor(model => model.FirstOrDefault().DOB)</p>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Pet item in Model)
            {
                <tr>
                    <td>
                        <p>@item.Name</p>
                    </td>
                    <td>
                        <p>@item.Kind</p>
                    </td>
                    <td>
                        <p>@item.Sex</p>
                    </td>
                    <td>
                        <p>@item.Breed</p>
                    </td>
                    <td>
                        <p>@item.DOB</p>
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary" asp-controller="Pet" asp-action="PetEdit" asp-route-id="@item.Id">Редактировать</a>
                        <form asp-controller="Pet" asp-action="PetDelete" asp-route-id="@item.Id">
                            <button class="btn btn-outline-danger">Удалить</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="PetRead"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-outline-secondary @prevDisabled">
        Пред
    </a>
    <a asp-action="PetRead"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-outline-secondary @nextDisabled">
        След
    </a>