VeterinaryPassport/Controllers/OwnerController.cs
using VeterinaryPassport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace VeterinaryPassport.Controllers
{
    [Authorize(Roles = "user")]
    public class OwnerController : Controller
    {
        Context db;
        public OwnerController(Context context)
        {
            db = context;
        }

        [HttpGet]
        public async Task<IActionResult> OwnerRead(string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var owner = db.Owners.Select(o => o);
            if (!String.IsNullOrEmpty(searchString))
                owner = owner.Where(s => s.Surname.Contains(searchString));
            int pageSize = 5;

            return View(await Pagination<Owner>.CreatePaginationAsync(owner, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult OwnerCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OwnerCreate(Owner owner)
        {
            if (ModelState.IsValid)
            {
                await db.Owners.AddAsync(owner);
                await db.SaveChangesAsync();

                return RedirectToAction("OwnerRead");
            }
            return View(owner);
        }

        [HttpGet]
        public async Task<IActionResult> OwnerEdit(int? id)
        {
            if (id != null)
            {
                Owner owner = await db.Owners.FirstOrDefaultAsync(o => o.Id == id);
                if (owner != null)
                    return View(owner);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> OwnerEdit(Owner owner)
        {
            if (ModelState.IsValid)
            {
                db.Owners.Update(owner);
                await db.SaveChangesAsync();

                return RedirectToAction("OwnerRead");
            }
            return View(owner);
        }

        [HttpPost]
        public async Task<IActionResult> OwnerDelete(int? id)
        {
            if (id != null)
            {
                Owner owner = await db.Owners.FirstOrDefaultAsync(o => o.Id == id);
                db.Owners.Remove(owner);
                await db.SaveChangesAsync();

                return RedirectToAction("OwnerRead");
            }
            return NotFound();
        }
    }
}

VeterinaryPassport/Controllers/PassportController.cs
using VeterinaryPassport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace VeterinaryPassport.Controllers
{
    [Authorize(Roles = "user")]
    public class PassportController : Controller
    {
        Context db;
        public PassportController(Context context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> PassportRead(string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var passport = db.Passports.Include(o => o.Owner).Include(p => p.Pet).Select(p => p);
            if (!String.IsNullOrEmpty(searchString))
                passport = passport.Where(s => s.Owner.Surname.Contains(searchString));

            int pageSize = 5;

            return View(await Pagination<Passport>.CreatePaginationAsync(passport, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult PassportCreate()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PassportCreate(Pet pet, int id)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Form.Files.FirstOrDefault();
                if (file != null)
                {
                    using (var stream = new FileStream(@"wwwroot\img\" + file.FileName, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    pet.ImageName = $"{file.FileName}";
                }
                else
                {
                    pet.ImageName = "no-image.jpg";
                }
                return RedirectToAction("PassportCreateNext", pet);
            }
            return View(pet);
        }

        [HttpGet]
        public async Task<IActionResult> PassportCreateNext(Pet pet, string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var owner = db.Owners.Select(o => o);
            if (!String.IsNullOrEmpty(searchString))
                owner = owner.Where(s => s.Surname.Contains(searchString));
            int pageSize = 5;
            ViewBag.pet = pet;

            return View(await Pagination<Owner>.CreatePaginationAsync(owner, pageNumber ?? 1, pageSize));
        }

        [HttpPost]
        public async Task<IActionResult> PassportCreateNext(string name, string breed, string kind, DateTime dob, string sex, int ownerId,string imageName)
        {
            Pet pet = new()
            {
                Name = name,
                Breed = breed,
                DOB = dob,
                Kind = kind,
                Sex = sex,
                ImageName = imageName
            };

            await db.Pets.AddAsync(pet);
            await db.SaveChangesAsync();

            Passport passport = new()
            {
                PetId = pet.Id,
                OwnerId = ownerId
            };

            await db.Passports.AddAsync(passport);
            await db.SaveChangesAsync();

            return RedirectToAction("PassportRead");
        }
        [HttpGet]
        public async Task<IActionResult> PassportEdit(int? id)
        {
            if (id != null)
            {
                Passport passport = await db.Passports.FirstOrDefaultAsync(p => p.Id == id);
                Pet pet = await db.Pets.FirstOrDefaultAsync(p => p.Id == passport.PetId);
                if(pet != null)
                {
                    return View(pet);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> PassportEdit(Pet pet)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Form.Files.FirstOrDefault();
                if (file != null)
                {
                    using (var stream = new FileStream(@"wwwroot\img\" + file.FileName, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    pet.ImageName = $"{file.FileName}";
                }
                else
                {
                    pet.ImageName = "Нет_фото.png";
                }
                db.Pets.Update(pet);
                await db.SaveChangesAsync();
                return RedirectToAction("PassportRead");
            }
            return View(pet);
        }
        [HttpGet]
        public async Task<IActionResult> PassportDetail(int? id)
        {
            Passport passport = await db.Passports.FirstOrDefaultAsync(p => p.Id == id);
            passport.Owner = await db.Owners.FirstOrDefaultAsync(o => o.Id == passport.OwnerId);
            passport.Pet = await db.Pets.FirstOrDefaultAsync(p => p.Id == passport.PetId);

            return View(passport);
        }

        [HttpPost]
        public async Task<IActionResult> PassportDelete(int? id)
        {
            if (id != null)
            {
                Passport passport = await db.Passports.FirstOrDefaultAsync(p => p.Id == id);
                Pet pet = await db.Pets.FirstOrDefaultAsync(p => p.Id == passport.PetId);
                db.Passports.Remove(passport);
                db.Pets.Remove(pet);
                await db.SaveChangesAsync();

                return RedirectToAction("PassportRead");
            }
            return NotFound();
        }
    }
}

VeterinaryPassport/Controllers/VetController.cs
using VeterinaryPassport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace VeterinaryPassport.Controllers
{
    [Authorize(Roles = "admin")]
    public class VetController : Controller
    {
        Context db;
        public VetController(Context context)
        {
            db = context;
        }

        [HttpGet]
        public async Task<IActionResult> VetRead(string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
           
            var vet = db.Vets.Select(v => v);
            int pageSize = 5;
            if (!String.IsNullOrEmpty(searchString))
                vet = vet.Where(s => s.Surname.Contains(searchString));

            return View(await Pagination<Vet>.CreatePaginationAsync(vet, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult VetCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> VetCreate(Vet vet)
        {
            if (ModelState.IsValid)
            {
                await db.Vets.AddAsync(vet);

                User user = new()
                {
                    Vet = vet,
                    Login = vet.Login,
                    Password = vet.Password,
                    VetId = vet.Id,
                    RoleId = 2
                };

                await db.Users.AddAsync(user);

                await db.SaveChangesAsync();

                return RedirectToAction("VetRead");
            }
            return View(vet);
        }

        [HttpGet]
        public async Task<IActionResult> VetEdit(int? id)
        {
            if (id != null)
            {
                Vet vet = await db.Vets.FirstOrDefaultAsync(v => v.Id == id);
                if (vet != null)
                    return View(vet);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> VetEdit(Vet vet)
        {
            if (ModelState.IsValid)
            {
                var user = await db.Users.FirstOrDefaultAsync(u => u.VetId == vet.Id);
                user.Login = vet.Login;
                user.Password = vet.Password;
                db.Users.Update(user);
                db.Vets.Update(vet);
                await db.SaveChangesAsync();

                return RedirectToAction("VetRead");
            }
            return View(vet);
        }

        [HttpPost]
        public async Task<IActionResult> VetDelete(int? id)
        {
            if (id != null)
            {
                Vet vet = await db.Vets.FirstOrDefaultAsync(v => v.Id == id);
                User user = await db.Users.FirstOrDefaultAsync(u => u.VetId == id);
                db.Vets.Remove(vet);
                db.Users.Remove(user);

                await db.SaveChangesAsync();

                return RedirectToAction("VetRead");
            }
            return NotFound();
        }
    }
}

VeterinaryPassport/Views/Shared/_Layout.cshtml
@inject Context context

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VeterinaryPassport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VeterinaryPassport.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Passport" asp-action="PassportRead">
                    <img src=~/img/paw-icon.png width="35" height="35" alt="Иконка лапки" />
                </a>
                <a class="navbar-brand link-color" asp-controller="Passport" asp-action="PassportRead">Главная</a>
                <a class="nav-link link-color" asp-controller="Vet" asp-action="VetRead">Ветеринары</a>
                <a class="nav-link link-color" asp-controller="Owner" asp-action="OwnerRead">Владельцы</a>
            </div>
            <div class="container-fluid2">
                @{
                    var vet = context.Vets.FirstOrDefault(v => v.Login == User.Identity.Name);
                    if (vet != null)
                    {
                        ViewData["Doc"] = User.Identity.Name == null ? Html.ActionLink("Войти", "Login", "Account", null, htmlAttributes: new { @class = "header-b" }) : "Пользователь " + vet?.Name + " " + vet?.Patronymic;
                    }
                    else
                    {
                        ViewData["Doc"] = User.Identity.Name == null ? Html.ActionLink("Войти", "Login", "Account", null, htmlAttributes: new { @class = "header-b" }) : "Пользователь " + User.Identity.Name;
                    }
                }
                <p class="header-a">@ViewData["Doc"] </p>
                @*Показать кнопку выход если человек авторизовался*@
                @if (ViewData["Doc"].GetType() == typeof(string))
                {
                    <a asp-controller="Account" asp-action="Lagout" class="header-a">
                        <button class="exit-button">
                            Выход
                        </button>
                    </a>
                }
            </div>
        </nav>
    </header>
    <div class="container main-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer-main footer text-muted">
        <div class="container footer">
            &copy; 2022 - VeterinaryPassport
        </div>
    </footer>

</body>
</html>